#!/usr/bin/env bash
# Author: qaraluch - XX.2019 - MIT

readonly _pDel='[ XXX ]'
readonly _pArgs="$@"
readonly _pName=$(basename $0)

printUsage() {
  cat <<EOL

  Help:
  ---------
  ${_cy}${_pName}${_ce} - YYY

  Usage:
    ${_pName} ${_cy}ZZZ${_ce}              - show list all packages (except of env ones).
                                example: QQQ

EOL
  exit ${1:-1}
}

# Utils:
readonly _cy=$'\033[1;33m'            # color yellow
readonly _cg=$'\033[1;32m'            # color green
readonly _ce=$'\033[0m'               # color end
readonly _cr=$'\033[0;31m'            # color red
readonly _it="[ ${_cg}✔${_ce} ]"      # icon tick
readonly _ic="[ ${_cr}✖${_ce} ]"      # icon cross

echoIt() {
  local delimiter=$1 ; local msg=$2 ; local icon=${3:-''} ; echo "${delimiter}${icon} $msg" >&2
}

echoDone() {
  echoIt "$_pDel" "DONE!" "$_it"
  echo >&2
}

errorExit() {
  local delimiter=$1 ; local msg=$2 ; local icon=${3:-"$_ic"} ; echo "${delimiter}${icon} ${msg}" 1>&2 ; exit 1
}


# CLI
parseOptions(){
  while [[ $# -gt 0 ]] ; do
    flag="$1"
    case $flag in
      -h|--help)
      printUsage
      ;;
      *)
      positional+=("$1")
      shift
      ;;
    esac
  done
}

main() {
  local positional=()
  parseOptions $_pArgs
  set -- "${positional[@]}"
  echoDone
}

main