#!/usr/bin/env bash
# Author: qaraluch - 07.2018 - MIT

readonly progName=$(basename $0)
readonly args="$@"

printUsage() {
  cat <<EOL
${progName} - Execute multiple commands from file.
               Handy when you need to extract clips from video.

Usage:
    ${progName} commands.txt
EOL
  exit $1
}

parseOptions() {
    while [[ $# -gt 0 ]]
    do
    key="$1"
    case $key in
        -h|--help)
        printUsage 1
        ;;
        *)                  # unknown option
        positional+=("$1")
        shift
        ;;
    esac
    done
}

isEmpty() {
    local var=$1
    [[ -z $var ]]
}

ifNoArgsPrintUsage() {
  isEmpty $1 \
      && printUsage 1
}

main() {
    local positional=()
    ifNoArgsPrintUsage $args
    parseOptions $args
    set -- "${positional[@]}"
    local cmdsFile=$1
    xargs -0 -n 1 bash -c < <(tr \\n \\0 < $cmdsFile)
}

main
